In [1]:
1 + 2

3

In [2]:
for _ in range(5) :
    print('Hello, Machine Learning!')

Hello, Machine Learning!
Hello, Machine Learning!
Hello, Machine Learning!
Hello, Machine Learning!
Hello, Machine Learning!


# 1、run:

In [3]:
%run functions/run.py

Hello %run


In [4]:
run("lvwei")

lvwei


# 2、Import Module:

In [5]:
from playML import Predict

In [6]:

Predict.predict(1)

?


# 3、 timeit:

In [7]:
%timeit L = [i**2 for i in range(1000)]

341 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%timeit L = [i**2 for i in range(1000000)]

345 ms ± 1.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%%timeit
L = []
for n in range(1000):
    L.append(n**2)

347 µs ± 3.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%%timeit
L = []
for n in range(1000000):
    L.append(n**2)

368 ms ± 1.52 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# 4、time:

In [11]:
%time L = [i**2 for i in range(1000)]

Wall time: 0 ns


In [12]:
%time L = [i**2 for i in range(1000000)]

Wall time: 347 ms


In [13]:
%%time
L = []
for n in range(1000):
    L.append(n**2)

Wall time: 14 ms


In [14]:
import random
L = [random.random() for i in range(1000000)]
%timeit L.sort()

23.9 ms ± 427 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
L = [random.random() for i in range(1000000)]
%timeit L.sort()

23.4 ms ± 508 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
import numpy
numpy.__version__

'1.17.2'

In [17]:
import numpy as np
np.__version__

'1.17.2'

In [18]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
L[5]

5

In [20]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [21]:
L[5] = 'Machine Learning'
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [22]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

# 5、 Numpy.array

In [24]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
len(nparr)

10

In [26]:
nparr.dtype

dtype('int32')

In [27]:
nparr[5] = 5.2
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.array.__doc__

"array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)\n\n    Create an array.\n\n    Parameters\n    ----------\n    object : array_like\n        An array, any object exposing the array interface, an object whose\n        __array__ method returns an array, or any (nested) sequence.\n    dtype : data-type, optional\n        The desired data-type for the array.  If not given, then the type will\n        be determined as the minimum type required to hold the objects in the\n        sequence.  This argument can only be used to 'upcast' the array.  For\n        downcasting, use the .astype(t) method.\n    copy : bool, optional\n        If true (default), then the object is copied.  Otherwise, a copy will\n        only be made if __array__ returns a copy, if obj is a nested sequence,\n        or if a copy is needed to satisfy any of the other requirements\n        (`dtype`, `order`, etc.).\n    order : {'K', 'A', 'C', 'F'}, optional\n        Specify the memory layout of the 

# 6、其他创建numpy.array的方法

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros(10).dtype

dtype('float64')

In [31]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones(shape=(3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.full(shape=(3,5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

# 7、arange

In [37]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [38]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 8、 linspace

In [41]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [42]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

# 9、random    

In [43]:
np.random.randint(0, 10)

5

In [44]:
np.random.randint(0, 10, 10)

array([4, 3, 1, 6, 0, 9, 6, 0, 1, 6])

In [45]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.random.randint(4, 8, size=10)

array([7, 4, 5, 6, 5, 5, 5, 7, 7, 5])

In [47]:
np.random.randint(4, 8, size=(3, 4))

array([[5, 4, 4, 5],
       [7, 5, 6, 5],
       [4, 5, 7, 6]])

In [48]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 4))

array([[4, 6, 5, 6],
       [6, 6, 5, 6],
       [4, 5, 7, 6]])

In [49]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 4))

array([[4, 6, 5, 6],
       [6, 6, 5, 6],
       [4, 5, 7, 6]])

In [50]:
np.random.seed(666)
np.random.random(10)

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796,
       0.0127032 , 0.4135877 , 0.04881279, 0.09992856, 0.50806631])

In [51]:
np.random.random((3, 5)) # 0-1 均匀分布

array([[0.20024754, 0.74415417, 0.192892  , 0.70084475, 0.29322811],
       [0.77447945, 0.00510884, 0.11285765, 0.11095367, 0.24766823],
       [0.0232363 , 0.72732115, 0.34003494, 0.19750316, 0.90917959]])

In [52]:
np.random.normal() # 0-1 均值为0，方差为1

0.028016723832884196

In [53]:
np.random.normal(10, 100) # 0-1 均值为10，方差为100

50.85571939822264

In [54]:
np.random.normal(0, 1, )

0.5392856473023979

In [55]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int or 

# 10、Numpy.array 的基本操作

In [56]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
x.ndim

1

In [59]:
X.ndim

2

In [60]:
x.shape

(10,)

In [61]:
X.shape

(3, 5)

In [62]:
x.size

10

In [63]:
X.size

15

## numpy.array 的数据访问

In [64]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x[0]

0

In [66]:
x[-1]

9

In [67]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
X[0][0] # 不建议的访问方式

0

In [69]:
X[(0, 1)]

1

In [70]:
X[2, 2]

12

In [71]:
x[0:5]

array([0, 1, 2, 3, 4])

In [72]:
x[:5]

array([0, 1, 2, 3, 4])

In [73]:
x[5:]

array([5, 6, 7, 8, 9])

In [74]:
x[2:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [75]:
x[::2]

array([0, 2, 4, 6, 8])

In [76]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [79]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [80]:
temp = X[:2]
temp

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
temp[:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [84]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
X[0, :]

array([0, 1, 2, 3, 4])

In [86]:
X[:, 0]

array([ 0,  5, 10])

In [87]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [88]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [89]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [90]:
help(subX.copy)

Help on built-in function copy:

copy(...) method of numpy.ndarray instance
    a.copy(order='C')
    
    Return a copy of the array.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout of the copy. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible. (Note that this function and :func:`numpy.copy` are very
        similar, but have different default values for their order=
        arguments.)
    
    See also
    --------
    numpy.copy
    numpy.copyto
    
    Examples
    --------
    >>> x = np.array([[1,2,3],[4,5,6]], order='F')
    
    >>> y = x.copy()
    
    >>> x.fill(0)
    
    >>> x
    array([[0, 0, 0],
           [0, 0, 0]])
    
    >>> y
    array([[1, 2, 3],
           [4, 5, 6]])
    
    >>> y.flags['C_CONTIGUOUS']
    True



In [91]:
subX = X[:2, :3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [92]:
subX[0, 0] = 0
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [93]:
X[0, 0]

100

## Reshape

In [94]:
x.shape

(10,)

In [95]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [98]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [99]:
B.shape

(1, 10)

In [100]:
x.shape

(10,)

In [101]:
x.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [103]:
print(x.reshape.__doc__)

a.reshape(shape, order='C')

    Returns an array containing the same data with a new shape.

    Refer to `numpy.reshape` for full documentation.

    See Also
    --------
    numpy.reshape : equivalent function

    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.


## 合并操作

In [104]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [105]:
x

array([1, 2, 3])

In [106]:
y

array([3, 2, 1])

In [107]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

In [108]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [109]:
z = np.array([666, 666, 666])
z

array([666, 666, 666])

In [110]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [112]:
np.concatenate([A, A], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [113]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [114]:
np.concatenate([A, z.reshape(1, 3)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [115]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [116]:
B = np.full((2, 2), fill_value=100)
B

array([[100, 100],
       [100, 100]])

In [117]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 分割操作

In [118]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
x1, x2, x3 = np.split(x, [3, 7])

In [120]:
x1

array([0, 1, 2])

In [121]:
x2

array([3, 4, 5, 6])

In [122]:
x3

array([7, 8, 9])

In [123]:
x1, x2 = np.split(x, [5])

In [124]:
x1

array([0, 1, 2, 3, 4])

In [125]:
x2

array([5, 6, 7, 8, 9])

In [126]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
A1, A2 = np.split(A, [2])

In [128]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [129]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [130]:
A1, A2 = np.split(A, [2], axis=1)

In [131]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [132]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [133]:
upper, lower = np.vsplit(A, [2])

In [134]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [135]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
left, right = np.hsplit(A, [2])

In [137]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [138]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [139]:
data = np.arange(16).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [140]:
x, y = np.hsplit(data, [-1])

In [141]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [142]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [143]:
y[:, 0]

array([ 3,  7, 11, 15])