# Scikit-learn中的Scaler

In [37]:
import numpy as np
from sklearn import datasets

In [38]:
iris = datasets.load_iris()

In [39]:
X = iris.data
Y = iris.target
X[:10, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=666)

## scikit-learn中的StandardScaler

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
stdScaler = StandardScaler()
stdScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [43]:
stdScaler.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [44]:
stdScaler.scale_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [45]:
X_train_standard = stdScaler.transform(X_train)
X_train_standard

array([[-0.90616043,  0.93246262, -1.30856471, -1.28788802],
       [-1.15301457, -0.19551636, -1.30856471, -1.28788802],
       [-0.16559799, -0.64670795,  0.22203084,  0.17260355],
       [ 0.45153738,  0.70686683,  0.95898425,  1.50032315],
       [-0.90616043, -1.32349533, -0.40154513, -0.09294037],
       [ 1.43895396,  0.25567524,  0.56216318,  0.30537551],
       [ 0.3281103 , -1.09789954,  1.0723617 ,  0.30537551],
       [ 2.1795164 , -0.19551636,  1.63924894,  1.23477923],
       [-0.78273335,  2.2860374 , -1.25187599, -1.42065998],
       [ 0.45153738, -2.00028272,  0.44878573,  0.43814747],
       [ 1.80923518, -0.42111215,  1.46918276,  0.83646335],
       [ 0.69839152,  0.25567524,  0.90229552,  1.50032315],
       [ 0.20468323,  0.70686683,  0.44878573,  0.57091943],
       [-0.78273335, -0.87230374,  0.10865339,  0.30537551],
       [-0.53587921,  1.38365421, -1.25187599, -1.28788802],
       [-0.65930628,  1.38365421, -1.25187599, -1.28788802],
       [-1.0295875 ,  0.

In [46]:
X_test_standard = stdScaler.transform(X_test)
X_test_standard

array([[-0.28902506, -0.19551636,  0.44878573,  0.43814747],
       [-0.04217092, -0.64670795,  0.78891808,  1.63309511],
       [-1.0295875 , -1.77468693, -0.23147896, -0.22571233],
       [-0.04217092, -0.87230374,  0.78891808,  0.96923531],
       [-1.52329579,  0.03007944, -1.25187599, -1.28788802],
       [-0.41245214, -1.32349533,  0.16534211,  0.17260355],
       [-0.16559799, -0.64670795,  0.44878573,  0.17260355],
       [ 0.82181859, -0.19551636,  0.8456068 ,  1.10200727],
       [ 0.57496445, -1.77468693,  0.39209701,  0.17260355],
       [-0.41245214, -1.09789954,  0.39209701,  0.03983159],
       [ 1.06867274,  0.03007944,  0.39209701,  0.30537551],
       [-1.64672287, -1.77468693, -1.36525344, -1.15511606],
       [-1.27644165,  0.03007944, -1.19518726, -1.28788802],
       [-0.53587921,  0.70686683, -1.25187599, -1.0223441 ],
       [ 1.68580811,  1.15805842,  1.35580532,  1.76586707],
       [-0.04217092, -0.87230374,  0.22203084, -0.22571233],
       [-1.52329579,  1.

In [47]:
from sklearn.neighbors import KNeighborsClassifier

In [48]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train_standard, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [49]:
knn_clf.score(X_test_standard, Y_test)

1.0

In [50]:
knn_clf.score(X_test, Y_test)

0.3333333333333333

In [51]:
from sklearn.preprocessing import MinMaxScaler

In [52]:
min_max_scaler = MinMaxScaler()
min_max_scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [53]:
min_max_scaler.min_

array([-1.19444444, -0.83333333, -0.19642857, -0.04166667])

In [54]:
min_max_scaler.data_max_

array([7.9, 4.4, 6.7, 2.5])

In [55]:
X_train_min_max = min_max_scaler.transform(X_train)
X_train_min_max

array([[0.22222222, 0.625     , 0.05357143, 0.04166667],
       [0.16666667, 0.41666667, 0.05357143, 0.04166667],
       [0.38888889, 0.33333333, 0.53571429, 0.5       ],
       [0.52777778, 0.58333333, 0.76785714, 0.91666667],
       [0.22222222, 0.20833333, 0.33928571, 0.41666667],
       [0.75      , 0.5       , 0.64285714, 0.54166667],
       [0.5       , 0.25      , 0.80357143, 0.54166667],
       [0.91666667, 0.41666667, 0.98214286, 0.83333333],
       [0.25      , 0.875     , 0.07142857, 0.        ],
       [0.52777778, 0.08333333, 0.60714286, 0.58333333],
       [0.83333333, 0.375     , 0.92857143, 0.70833333],
       [0.58333333, 0.5       , 0.75      , 0.91666667],
       [0.47222222, 0.58333333, 0.60714286, 0.625     ],
       [0.25      , 0.29166667, 0.5       , 0.54166667],
       [0.30555556, 0.70833333, 0.07142857, 0.04166667],
       [0.27777778, 0.70833333, 0.07142857, 0.04166667],
       [0.19444444, 0.625     , 0.08928571, 0.20833333],
       [0.02777778, 0.375     ,

In [56]:
X_test_min_max = min_max_scaler.transform(X_test)
X_test_min_max

array([[ 0.36111111,  0.41666667,  0.60714286,  0.58333333],
       [ 0.41666667,  0.33333333,  0.71428571,  0.95833333],
       [ 0.19444444,  0.125     ,  0.39285714,  0.375     ],
       [ 0.41666667,  0.29166667,  0.71428571,  0.75      ],
       [ 0.08333333,  0.45833333,  0.07142857,  0.04166667],
       [ 0.33333333,  0.20833333,  0.51785714,  0.5       ],
       [ 0.38888889,  0.33333333,  0.60714286,  0.5       ],
       [ 0.61111111,  0.41666667,  0.73214286,  0.79166667],
       [ 0.55555556,  0.125     ,  0.58928571,  0.5       ],
       [ 0.33333333,  0.25      ,  0.58928571,  0.45833333],
       [ 0.66666667,  0.45833333,  0.58928571,  0.54166667],
       [ 0.05555556,  0.125     ,  0.03571429,  0.08333333],
       [ 0.13888889,  0.45833333,  0.08928571,  0.04166667],
       [ 0.30555556,  0.58333333,  0.07142857,  0.125     ],
       [ 0.80555556,  0.66666667,  0.89285714,  1.        ],
       [ 0.41666667,  0.29166667,  0.53571429,  0.375     ],
       [ 0.08333333,  0.

In [57]:
knn_clf2 = KNeighborsClassifier(n_neighbors=3)
knn_clf2.fit(X_train_min_max, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [58]:
knn_clf2.score(X_test_min_max, Y_test)

1.0