# 聚合操作

In [6]:
import numpy as np
L = np.random.random(100)
L

array([3.88066074e-01, 4.88537640e-01, 8.86591395e-01, 1.26327408e-01,
       9.55438385e-01, 8.18745160e-01, 7.37458906e-01, 1.67909871e-01,
       4.09815804e-01, 1.76623113e-01, 1.04332412e-01, 9.58265733e-01,
       4.62097182e-01, 5.82409914e-01, 2.85989817e-01, 6.57596406e-01,
       8.79313552e-01, 6.25509460e-01, 2.68044512e-01, 4.85841825e-01,
       5.51543369e-01, 4.19652319e-01, 7.36300020e-01, 3.52036650e-01,
       7.30294920e-01, 3.69190205e-01, 4.55412382e-01, 7.47790926e-01,
       3.15113556e-01, 8.13821043e-01, 3.43332954e-01, 7.35609007e-01,
       6.31828908e-01, 3.33233466e-01, 7.36632442e-01, 6.11234579e-01,
       6.56911324e-02, 4.17470735e-01, 6.05226441e-01, 6.19607160e-01,
       3.51551095e-01, 8.69493280e-01, 4.73191130e-01, 4.52711442e-02,
       1.03023266e-01, 2.32650827e-01, 1.79798806e-01, 3.77361293e-01,
       3.66928754e-01, 2.72529780e-01, 1.16117618e-01, 7.47308446e-01,
       2.31277451e-01, 3.99159271e-01, 5.02916094e-01, 5.86262472e-01,
      

In [7]:
sum(L)

48.60613493807235

In [8]:
np.sum(L)

48.60613493807233

In [9]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

138 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
930 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
np.min(big_array)

4.5057697439787603e-07

In [12]:
big_array.min()

4.5057697439787603e-07

In [13]:
np.max(big_array)

0.9999996512923084

In [14]:
big_array.max()

0.9999996512923084

In [15]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.sum(X)

120

In [17]:
np.sum(X, axis=0)       # “沿着” 行(第0维)进行计算

array([24, 28, 32, 36])

In [18]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [19]:
np.prod(X)

0

In [20]:
np.prod(X + 1)

2004189184

In [21]:
np.mean(X)

7.5

In [22]:
np.median(X)        # 平均值

7.5

In [23]:
np.median(X)        # 中位数

7.5

In [28]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [29]:
np.median(v)

2.0

In [30]:
np.percentile(big_array, q=50)      # 前50个最小值

0.5004389962802471

In [31]:
np.median(big_array)

0.5004389962802471

In [32]:
np.percentile(big_array, q=100)  

0.9999996512923084

In [34]:
for precent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=precent))

4.5057697439787603e-07
0.2505716423329921
0.5004389962802471
0.7499527682874683
0.9999996512923084


In [44]:
np.var(big_array)      #方差

0.08319880004900913

In [45]:
np.std(big_array) * np.std(big_array)       #标准差

0.08319880004900915

In [40]:
x = np.random.normal(0, 1, size=1000000) 

In [41]:
np.mean(x)

0.0014091494970250808

In [42]:
np.std(x)

1.0000081117393582