# 聚合操作

In [1]:
import numpy as np
L = np.random.random(100)
L

array([0.14931386, 0.26960485, 0.84856435, 0.51929775, 0.60405002,
       0.52743863, 0.61954265, 0.37925503, 0.91469718, 0.09510817,
       0.92798963, 0.7521695 , 0.56042824, 0.47849338, 0.41009038,
       0.5295221 , 0.93255552, 0.74773718, 0.22087959, 0.30267734,
       0.70498217, 0.88113277, 0.86084136, 0.92984257, 0.17290845,
       0.36927805, 0.61981383, 0.16530815, 0.63792812, 0.81783104,
       0.97298119, 0.24917941, 0.48834078, 0.86805939, 0.30737456,
       0.69728077, 0.75908202, 0.04883381, 0.775229  , 0.27468173,
       0.42511638, 0.55127415, 0.72038059, 0.13676987, 0.12860989,
       0.35790247, 0.06372543, 0.34822874, 0.60164599, 0.50580732,
       0.38940376, 0.52355472, 0.6439862 , 0.07089837, 0.34611249,
       0.53689696, 0.12966819, 0.64006982, 0.09863033, 0.21214377,
       0.34849249, 0.54598704, 0.36832269, 0.38991173, 0.9692813 ,
       0.32542666, 0.70436439, 0.57902896, 0.7690345 , 0.11835029,
       0.12868351, 0.10950874, 0.11043292, 0.46297296, 0.99493

In [2]:
sum(L)

48.09250300056938

In [3]:
np.sum(L)

48.09250300056937

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

71.8 ms ± 1.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.12 ms ± 5.61 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
np.min(big_array)

2.2622610706957147e-07

In [6]:
big_array.min()

2.2622610706957147e-07

In [7]:
np.max(big_array)

0.9999991149610526

In [8]:
big_array.max()

0.9999991149610526

In [9]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.sum(X)

120

In [11]:
np.sum(X, axis=0)       # “沿着” 行(第0维)进行计算

array([24, 28, 32, 36])

In [12]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [13]:
np.prod(X)

0

In [14]:
np.prod(X + 1)

2004189184

In [15]:
np.mean(X)

7.5

In [16]:
np.median(X)        # 平均值

7.5

In [17]:
np.median(X)        # 中位数

7.5

In [18]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [19]:
np.median(v)

2.0

In [20]:
np.percentile(big_array, q=50)      # 前50个最小值

0.4992875796840776

In [21]:
np.median(big_array)

0.4992875796840776

In [22]:
np.percentile(big_array, q=100)  

0.9999991149610526

In [23]:
for precent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=precent))

2.2622610706957147e-07
0.2503552557668224
0.4992875796840776
0.7494084316616495
0.9999991149610526


In [24]:
np.var(big_array)      #方差

0.08318908729379164

In [25]:
np.std(big_array) * np.std(big_array)       #标准差

0.08318908729379165

In [26]:
x = np.random.normal(0, 1, size=1000000) 

In [27]:
np.mean(x)

-0.0007167879705186277

In [28]:
np.std(x)

0.9998384209966213