# 梯度下降法的向量化

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
boston = datasets.load_boston()
X = boston.data
Y = boston.target

X = X[Y < 50.0]
Y = Y[Y < 50.0]

In [3]:
from playML.train_test_split_self import train_test_split_self

X_train, X_test, Y_train, Y_test = train_test_split_self(X, Y, seed=666)

In [4]:
from playML.LinearRegression import LinearRegression

lin_reg1 = LinearRegression()
%time lin_reg1.fit_normal(X_train, Y_train)
lin_reg1.score(X_test, Y_test)

Wall time: 41.9 ms


0.8129794056212711

## 梯度下降法训练模型

In [5]:
lin_reg2 = LinearRegression()
lin_reg2.fit_gd(X_train, Y_train)

C:\Python37\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
f:\科学研究\jupyter workspace\ML-Learning\playML\LinearRegression.py:27: RuntimeWarning: overflow encountered in square
  return np.sum((y - X_b.dot(theta)) ** 2) / len(y)
f:\科学研究\jupyter workspace\ML-Learning\playML\LinearRegression.py:49: RuntimeWarning: invalid value encountered in double_scalars
  if(abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):


LinearRegression()

In [6]:
X_train[:10, :]

array([[1.42362e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.93000e-01,
        6.34300e+00, 1.00000e+02, 1.57410e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.96900e+02, 2.03200e+01],
       [3.67822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.70000e-01,
        5.36200e+00, 9.62000e+01, 2.10360e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.80790e+02, 1.01900e+01],
       [1.04690e-01, 4.00000e+01, 6.41000e+00, 1.00000e+00, 4.47000e-01,
        7.26700e+00, 4.90000e+01, 4.78720e+00, 4.00000e+00, 2.54000e+02,
        1.76000e+01, 3.89250e+02, 6.05000e+00],
       [1.15172e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        5.70100e+00, 9.50000e+01, 3.78720e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.58770e+02, 1.83500e+01],
       [6.58800e-02, 0.00000e+00, 2.46000e+00, 0.00000e+00, 4.88000e-01,
        7.76500e+00, 8.33000e+01, 2.74100e+00, 3.00000e+00, 1.93000e+02,
        1.78000e+01, 3.95560e+02, 7.56000e+00],
       [2.49800e-02, 0.00000e+

In [7]:
lin_reg2.fit_gd(X_train, Y_train, eta=0.000001, n_iters=1e6)

LinearRegression()

In [8]:
lin_reg2.coef_

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

## 数据归一化

In [9]:
from sklearn.preprocessing import StandardScaler
stdScaler = StandardScaler()
stdScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
X_train_standard = stdScaler.transform(X_train)

In [11]:
lin_reg3 = LinearRegression()
%time lin_reg3.fit_gd(X_train_standard, Y_train)


Wall time: 160 ms


LinearRegression()

In [12]:
X_test_standard = stdScaler.transform(X_test)

In [13]:
lin_reg3.score(X_test_standard, Y_test)

0.8129873310487505

In [14]:
lin_reg3.coef_

array([-1.04042202,  0.83093351, -0.24794356,  0.01179456, -1.35034756,
        2.25074   , -0.66384353, -2.53568774,  2.25572406, -2.34011572,
       -1.76565394,  0.70923397, -2.72677064])

## 梯度下降法的优势

In [15]:
m = 1000
n = 10000

big_X = np.random.normal(size=(m, n))
true_theta = np.random.uniform(0.0, 100.0, size=n+1)
big_Y = big_X.dot(true_theta[1:]) + true_theta[0] + np.random.normal(0., 10., size=m)

In [16]:
big_reg1 = LinearRegression()
%time big_reg1.fit_normal(big_X, big_Y)

Wall time: 28 s


LinearRegression()

In [17]:
big_reg2 = LinearRegression()
%time big_reg2.fit_gd(big_X, big_Y)

Wall time: 3.25 s


LinearRegression()