# 索引

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, size=1000000)

In [3]:
np.min(x)

-4.916472215678763

In [4]:
np.argmin(x)            # 值所在的索引

449018

In [5]:
x[np.argmin(x)]

-4.916472215678763

In [7]:
np.argmax(x)

475603

In [8]:
x[np.argmax(x)]

4.856350102790194

## 排序和使用索引

In [10]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
np.random.shuffle(x) #乱序操作
x

array([ 2,  5,  8,  0, 15,  4, 12, 13,  7,  6, 14, 11,  1, 10,  9,  3])

In [12]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
X = np.random.randint(10, size=(4, 4))
X

array([[4, 1, 1, 4],
       [4, 5, 8, 5],
       [6, 8, 2, 2],
       [9, 1, 8, 5]])

In [15]:
np.sort(X)

array([[1, 1, 4, 4],
       [4, 5, 5, 8],
       [2, 2, 6, 8],
       [1, 5, 8, 9]])

In [16]:
np.sort(X, axis=0)

array([[4, 1, 1, 2],
       [4, 1, 2, 4],
       [6, 5, 8, 5],
       [9, 8, 8, 5]])

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
np.random.shuffle(x)
x

array([10,  2,  6,  9, 14, 15,  8,  5,  1,  4, 13, 11, 12,  7,  0,  3])

In [24]:
np.argsort(x)

array([14,  8,  1, 15,  9,  7,  2, 13,  6,  3,  0, 11, 12, 10,  4,  5],
      dtype=int64)

In [25]:
np.partition(x, 3)      # 快速排序，一次标定点排序

array([ 0,  1,  2,  3,  4,  5,  8, 15, 14,  9, 13, 11, 12,  7,  6, 10])

In [26]:
np.argpartition(x, 3)

array([14,  8,  1, 15,  9,  7,  6,  5,  4,  3, 10, 11, 12, 13,  2,  0],
      dtype=int64)

In [27]:
X

array([[4, 1, 1, 4],
       [4, 5, 8, 5],
       [6, 8, 2, 2],
       [9, 1, 8, 5]])

In [28]:
np.argsort(X, axis=1)

array([[1, 2, 0, 3],
       [0, 1, 3, 2],
       [2, 3, 0, 1],
       [1, 3, 2, 0]], dtype=int64)

In [29]:
np.argpartition(X, 2)

array([[1, 2, 0, 3],
       [0, 1, 3, 2],
       [2, 3, 0, 1],
       [1, 3, 2, 0]], dtype=int64)

In [30]:
np.argpartition(X, 2, axis=0)

array([[0, 0, 0, 2],
       [1, 3, 2, 0],
       [2, 1, 1, 1],
       [3, 2, 3, 3]], dtype=int64)