# Fancy Indexing

In [43]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
x[3]

3

In [45]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [46]:
x[3:9:2]

array([3, 5, 7])

In [47]:
[x[3], x[5], x[8]]

[3, 5, 8]

In [48]:
ind = [3, 5, 8]

In [49]:
x[ind]

array([3, 5, 8])

In [50]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [51]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [53]:
X[0, col]

array([1, 2, 3])

In [54]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [55]:
rc = np.array([(0, 1), (2, 3)])
X[rc]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [56]:
col = [True, False, True, True]

In [57]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 的比较

In [58]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [60]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [61]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [62]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [63]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [64]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [65]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [67]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
np.sum(x <= 3)

4

In [69]:
np.count_nonzero(x <= 3)        # 统计方法

4

In [70]:
np.any(x == 0)

True

In [71]:
np.all(x >= 0)

True

In [72]:
np.all(x > 0)

False

In [73]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.sum(X % 2 == 0)

8

In [75]:
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [76]:
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [77]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [78]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
np.sum((x > 3) & (x < 10)) # 使用"&"运算符

6

In [80]:
np.sum((x % 2 == 0) | (x > 10)) 

11

In [81]:
np.sum(~(x == 0))

15

In [82]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [83]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [84]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
X[:, -1] % 3 == 0

array([ True, False, False,  True])

In [92]:
X[X[:, -1] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])