# F1 Score

In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
def f1_score(precision, recall):
    try: 
        return 2*precision*recall / (precision + recall)
    except:
        return 0.0

In [25]:
precision = 0.5
recall = 0.5

f1_score(precision, recall)

0.5

In [26]:
precision = 0.1
recall = 0.9

f1_score(precision, recall)

0.18000000000000002

In [27]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [29]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg.score(X_test, y_test)

0.9755555555555555

In [30]:
y_predict = log_reg.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [32]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [33]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [34]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

## 精准率与召回率的平衡

In [35]:
log_reg.decision_function(X_test)

array([-22.05698872, -33.0294801 , -16.21340124, -80.37927135,
       -48.2512484 , -24.54011888, -44.39165518, -25.04307342,
        -0.97825932, -19.7175234 , -66.25139047, -51.09618762,
       -31.49353062, -46.05326549, -38.67891437, -29.80475821,
       -37.58859784, -82.5757588 , -37.81913688, -11.01165136,
        -9.17440891, -85.13009105, -16.71605329, -46.23739157,
        -5.33004151, -47.91760576, -11.66736692, -39.19642117,
       -25.25302546, -14.36644282, -16.99792558, -28.91917652,
       -34.33955757, -29.47642261,  -7.85813385,  -3.82079588,
       -24.08193513, -22.16361045, -33.61241617, -23.14032762,
       -26.91815785, -62.38948524, -38.85707838, -66.77271748,
       -20.14486056, -17.47888542, -18.06800584, -22.22236762,
       -29.62315097, -19.73166906,   1.49551355,   8.32089659,
       -36.29344303, -42.50742316, -25.90456531, -34.98970987,
        -8.42024407, -50.04735304, -51.48216029,  19.88973194,
        -8.91891746, -31.99354552, -11.66113907,  -0.47

In [36]:
log_reg.decision_function(X_test)[:10]

array([-22.05698872, -33.0294801 , -16.21340124, -80.37927135,
       -48.2512484 , -24.54011888, -44.39165518, -25.04307342,
        -0.97825932, -19.7175234 ])

In [37]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
decision_scores = log_reg.decision_function(X_test)

In [39]:
y_predict_2 = np.array(decision_scores >=5, dtype='int')

In [40]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]], dtype=int64)

In [41]:
precision_score(y_test, y_predict_2)

0.96

In [42]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [43]:
y_predict_3 = np.array(decision_scores >=-5, dtype='int')

In [44]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]], dtype=int64)

In [45]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [46]:
recall_score(y_test, y_predict_3)

0.8888888888888888