# 测试算法

In [110]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [111]:
iris = datasets.load_iris()

In [112]:
X = iris.data
Y = iris.target

In [113]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [114]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## train_test_split(训练数据集、测试数据集拆分)

In [115]:
shuffile_indexes = np.random.permutation(len(X))
shuffile_indexes

array([144, 100, 101,   5,  36,  54,  96,  75,  59, 133,  62, 128,  30,
        88, 141,   1, 135, 146, 126,  43,  98,  38, 137,  27,  51,  61,
       121,  12,  49,  90,  47,  14,   8,  77, 110,  34,  21,  95,  86,
        68, 129,  16,  46, 138,  57,  15,  83,  29,  19,  74,  26,  13,
       124,  72,  73,  78,  45, 136,  91,  44, 142,   3,  82,  41,  52,
       113,  32, 107, 132, 123, 102, 147,  99,  22,  50, 125, 115,  24,
        64, 117, 134, 112,  71, 143,  53,   0, 139, 118,  28,  92, 145,
         7,  97, 149,  85,  81,  84,   2, 130, 114, 140,  35,  70,  11,
       148,  10, 120, 109,  23,  56, 111,  33,  80,  18, 119, 108,  39,
        94, 131,  40,   9, 127, 103,  58,  87, 122,  37,  20,  17,  69,
        93,  67,  65, 104,  25,  76, 105,   4,   6,  42,  79,  55, 106,
        60,  89,  66,  63, 116,  48,  31])

In [116]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)
test_size

30

In [117]:
test_indexes = shuffile_indexes[:test_size]
test_indexes

array([144, 100, 101,   5,  36,  54,  96,  75,  59, 133,  62, 128,  30,
        88, 141,   1, 135, 146, 126,  43,  98,  38, 137,  27,  51,  61,
       121,  12,  49,  90])

In [118]:
train_indexes = shuffile_indexes[test_size:]
train_indexes

array([ 47,  14,   8,  77, 110,  34,  21,  95,  86,  68, 129,  16,  46,
       138,  57,  15,  83,  29,  19,  74,  26,  13, 124,  72,  73,  78,
        45, 136,  91,  44, 142,   3,  82,  41,  52, 113,  32, 107, 132,
       123, 102, 147,  99,  22,  50, 125, 115,  24,  64, 117, 134, 112,
        71, 143,  53,   0, 139, 118,  28,  92, 145,   7,  97, 149,  85,
        81,  84,   2, 130, 114, 140,  35,  70,  11, 148,  10, 120, 109,
        23,  56, 111,  33,  80,  18, 119, 108,  39,  94, 131,  40,   9,
       127, 103,  58,  87, 122,  37,  20,  17,  69,  93,  67,  65, 104,
        25,  76, 105,   4,   6,  42,  79,  55, 106,  60,  89,  66,  63,
       116,  48,  31])

In [119]:
X_train = X[train_indexes]
Y_train = Y[train_indexes]

X_test = X[test_indexes]
Y_test = Y[test_indexes]

In [120]:
X_train.shape

(120, 4)

In [121]:
X_test.shape

(30, 4)

## 使用我们的算法

In [170]:
from playML.train_test_split_self import train_test_split_self
from playML.kNNClassifier import KNNClassifier

In [171]:
X_train, X_test, Y_train, Y_test = train_test_split_self(X, Y)
print(X_train.shape)
print(Y_train.shape)

(120, 4)
(120,)


In [172]:
knn_clf = KNNClassifier(k=3)
knn_clf.fit(X_train, Y_train)
y_predict = knn_clf.predict(X_test)

In [173]:
y_predict

array([1, 2, 1, 1, 1, 1, 0, 1, 2, 2, 0, 1, 0, 0, 2, 0, 1, 0, 0, 2, 1, 2,
       1, 1, 2, 0, 2, 1, 0, 2])

In [174]:
sum(y_predict == Y_test)

28

In [175]:
sum(y_predict == Y_test) / len(Y_test)

0.9333333333333333

## sklearn中的train_test_split

In [176]:
from sklearn.model_selection import train_test_split

In [177]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
print(X_train.shape)
print(Y_train.shape)

(120, 4)
(120,)


In [178]:
from sklearn.neighbors import KNeighborsClassifier

In [179]:
kNN_classifier = KNeighborsClassifier(n_neighbors=3)
kNN_classifier.fit(X_train, Y_train)    # 拟合训练数据模型

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')