# 测试算法

In [23]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [24]:
iris = datasets.load_iris()

In [25]:
X = iris.data
Y = iris.target

In [26]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## train_test_split(训练数据集、测试数据集拆分)

In [28]:
shuffile_indexes = np.random.permutation(len(X))
shuffile_indexes

array([136,  85,   3,  76,  95, 141,  93,  44,  13, 108,  49,  21,  70,
        11,  42,  22, 127,   9, 147,  36,  40,  91, 115, 116,  65,   6,
       128,  26, 113, 106,  57,  78, 102, 145,  48,  31,  56, 122,  90,
       117, 133,  20, 140, 123,  84, 112, 107,  63,  67,   0,   5,  55,
        10,  53,  61, 146,  39, 142,  82, 124,  58,  19,  46, 100,  86,
        27,  62, 137,  92, 149, 110,  15,  52, 103, 105, 126, 130,  18,
        75,  81,  28, 131, 114,  29, 118,  17,  24, 104,  47,  71, 138,
        80, 129,  16,  34, 134, 139, 132,  60,  50,  14,   8,  99,  41,
        23,  83, 111,  25,  32,  77, 101,  59,  89,  12,   7,  54,  73,
         1, 144,  87,  35,  37, 135,  33,  72,   2, 121,  88,  69, 125,
        96,   4,  38,  79,  68,  45,  97, 109, 120,  94, 119,  30,  51,
       148,  98,  64, 143,  74,  43,  66])

In [29]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)
test_size

30

In [30]:
test_indexes = shuffile_indexes[:test_size]
test_indexes

array([136,  85,   3,  76,  95, 141,  93,  44,  13, 108,  49,  21,  70,
        11,  42,  22, 127,   9, 147,  36,  40,  91, 115, 116,  65,   6,
       128,  26, 113, 106])

In [31]:
train_indexes = shuffile_indexes[test_size:]
train_indexes

array([ 57,  78, 102, 145,  48,  31,  56, 122,  90, 117, 133,  20, 140,
       123,  84, 112, 107,  63,  67,   0,   5,  55,  10,  53,  61, 146,
        39, 142,  82, 124,  58,  19,  46, 100,  86,  27,  62, 137,  92,
       149, 110,  15,  52, 103, 105, 126, 130,  18,  75,  81,  28, 131,
       114,  29, 118,  17,  24, 104,  47,  71, 138,  80, 129,  16,  34,
       134, 139, 132,  60,  50,  14,   8,  99,  41,  23,  83, 111,  25,
        32,  77, 101,  59,  89,  12,   7,  54,  73,   1, 144,  87,  35,
        37, 135,  33,  72,   2, 121,  88,  69, 125,  96,   4,  38,  79,
        68,  45,  97, 109, 120,  94, 119,  30,  51, 148,  98,  64, 143,
        74,  43,  66])

In [32]:
X_train = X[train_indexes]
Y_train = Y[train_indexes]

X_test = X[test_indexes]
Y_test = Y[test_indexes]

In [33]:
X_train.shape

(120, 4)

In [34]:
X_test.shape

(30, 4)

## 使用我们的算法

In [35]:
from playML.train_test_split_self import train_test_split_self
from playML.kNNClassifier import KNNClassifier

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split_self(X, Y)
print(X_train.shape)
print(Y_train.shape)

(120, 4)
(120,)


In [37]:
knn_clf = KNNClassifier(k=3)
knn_clf.fit(X_train, Y_train)
y_predict = knn_clf.predict(X_test)

In [38]:
y_predict

array([1, 2, 1, 1, 1, 2, 1, 1, 0, 2, 0, 2, 0, 1, 0, 2, 1, 0, 2, 2, 1, 0,
       0, 1, 1, 2, 0, 1, 0, 0])

In [39]:
sum(y_predict == Y_test)

29

In [40]:
sum(y_predict == Y_test) / len(Y_test)

0.9666666666666667

## sklearn中的train_test_split

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
print(X_train.shape)
print(Y_train.shape)

(120, 4)
(120,)


In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
kNN_classifier = KNeighborsClassifier(n_neighbors=3)
kNN_classifier.fit(X_train, Y_train)    # 拟合训练数据模型

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')